### ISSUE TITLE
CSS Design

### ISSUE THREAD

**Issue by bruceanthonyii** [Craig5117/critter#3]
Comment Form
Comment List
Footer
Friends List
Header
Nav
Pet Card
Post Form
Post List
Profile Image
React Bootstrap Login Form for Login.js and Signup.js

**Comment by Craig5117** [comment]
So far,  I believe Sydney has offered to take on the Header and Nav.
Bruce is going to start with the Login and Signup pages.
Jessica is starting with the PetCard.
